import Head from "next/head";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { getCookie, setCookies, removeCookies } from "cookies-next";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  //console.log(getCookie("autha"));

  if (typeof window !== "undefined") {
    // Client-side-only code
    if (getCookie("auth")) {
      router.push("/dashboard");
    }
  }
  return (
    <div>
      <Head>
        <title>Create Vikas Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main data-theme="light">
        <Navbar openSideBar={null} />
        <Hero />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
